name: Build and Package Executables

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  # Change to windows-latest or macos-latest if targeting those OS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Specify the Python version you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean build directories
        run: rm -rf build dist

      - name: Build executable
        run: pyinstaller SpotifyGestureController.spec

      - name: Copy additional files
        run: |
          cp Gesture_Control.task dist/
          cp Tutorial.png dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            dist/
            Gesture_Control.task
            Tutorial.png