name: Build Executables

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Clean build directories
        run: |
          if (Test-Path -Path build) { Remove-Item -Recurse -Force build }
          if (Test-Path -Path dist) { Remove-Item -Recurse -Force dist }
      - name: Build executable
        run: pyinstaller SpotifyGestureController_windows.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: dist/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Clean build directories
        run: rm -rf build dist
      - name: Build executable
        run: pyinstaller SpotifyGestureController_linux.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-executable
          path: dist/

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Clean build directories
        run: rm -rf build dist
      - name: Build executable
        run: pyinstaller SpotifyGestureController_mac.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-executable
          path: dist/